// Pre-cached English definitions for vocabulary quest (G1-G5, 872 words)
// Curated knowledge base — zero external API dependency at runtime
(function () {
  const data = {
  "g1-u01-bold": [["adjective","courageous and confident"],["adjective","striking and bold in appearance"]],
  "g1-u01-coward": [["noun","a person who lacks courage"]],
  "g1-u01-flee": [["verb","run away quickly from danger"]],
  "g1-u01-fortune": [["noun","chance or luck"],["noun","a large amount of money or possessions"]],
  "g1-u01-gasp": [["verb","breathe in suddenly with open mouth"],["noun","a sudden intake of breath"]],
  "g1-u01-grin": [["verb","smile widely"],["noun","a wide smile"]],
  "g1-u01-sharp": [["adjective","having a fine cutting edge"],["adjective","quick and alert"]],
  "g1-u01-sneaky": [["adjective","secretive and dishonest"]],
  "g1-u01-stare": [["verb","look fixedly with wide eyes"],["noun","a fixed look"]],
  "g1-u02-dart": [["verb","move suddenly and quickly"],["noun","a small pointed missile"]],
  "g1-u02-gulp": [["verb","swallow quickly"],["noun","a large swallow"]],
  "g1-u02-host": [["noun","a person who receives guests"],["noun","a large number of people or things"]],
  "g1-u02-rude": [["adjective","not polite or respectful"]],
  "g1-u02-scold": [["verb","rebuke someone angrily"]],
  "g1-u02-serious": [["adjective","sincere and earnest"],["adjective","grave or important"]],
  "g1-u02-sly": [["adjective","cunning and deceitful"]],
  "g1-u02-upset": [["verb","knock over"],["adjective","distressed or disturbed"]],
  "g1-u02-weary": [["adjective","tired"]],
  "g1-u03-complain": [["verb","express dissatisfaction"]],
  "g1-u03-yank": [["verb","pull suddenly and hard"]],
  "g1-u04-cozy": [["adjective","warm and comfortable"]],
  "g1-u04-fierce": [["adjective","showing a heartfelt and powerful intensity"],["adjective","violent and dangerous"]],
  "g1-u04-hatch": [["verb","come out of an egg"],["verb","devise a scheme secretly"]],
  "g1-u04-howl": [["verb","make a loud wailing sound"]],
  "g1-u04-huddle": [["verb","crowd together closely"]],
  "g1-u04-hunt": [["verb","chase and kill for food or sport"],["noun","an act of hunting"]],
  "g1-u05-blush": [["verb","become red in the face from embarrassment"]],
  "g1-u05-chatter": [["verb","talk rapidly and continuously"],["noun","rapid talk"]],
  "g1-u05-doze": [["verb","sleep lightly"]],
  "g1-u05-drench": [["verb","soak thoroughly"]],
  "g1-u05-dusk": [["noun","the darker stage of twilight"]],
  "g1-u05-peer": [["verb","look carefully"],["noun","a person of the same age or status"]],
  "g1-u05-slippery": [["adjective","difficult to walk on because smooth and wet"]],
  "g1-u05-startle": [["verb","cause to feel sudden shock or alarm"]],
  "g1-u05-stumble": [["verb","trip and almost fall"]],
  "g1-u05-swift": [["adjective","happening quickly or promptly"]],
  "g1-u06-burst": [["verb","break open suddenly"],["noun","a sudden outbreak"]],
  "g1-u06-examine": [["verb","inspect carefully"]],
  "g1-u06-fasten": [["verb","close securely"]],
  "g1-u06-frantic": [["adjective","wildly excited or anxious"]],
  "g1-u06-judge": [["verb","form an opinion about"],["noun","a public officer who presides over a court"]],
  "g1-u06-shock": [["verb","surprise greatly"],["noun","a sudden upsetting event"]],
  "g1-u06-space": [["noun","the boundless expanse where objects exist"],["noun","a gap or empty area"]],
  "g1-u06-spread": [["verb","open out wider"],["verb","distribute or scatter"]],
  "g1-u06-squirm": [["verb","wriggle from discomfort or embarrassment"]],
  "g1-u06-tangle": [["verb","twist together into a confused mass"],["noun","a confused mass"]],
  "g1-u07-applause": [["noun","encouragement shown by clapping hands"]],
  "g1-u07-instrument": [["noun","a tool used for particular purpose"],["noun","a device for making music"]],
  "g1-u07-lively": [["adjective","full of energy and excitement"]],
  "g1-u07-nervous": [["adjective","easily agitated or alarmed"]],
  "g1-u07-perform": [["verb","carry out an action"],["verb","present an entertainment to an audience"]],
  "g1-u07-role": [["noun","the function someone or something has"],["noun","a part played by an actor"]],
  "g1-u07-shriek": [["verb","utter a high-pitched piercing sound"]],
  "g1-u07-sway": [["verb","move slowly back and forth"],["verb","influence or control"]],
  "g1-u07-timid": [["adjective","showing a lack of courage"]],
  "g1-u07-whirl": [["verb","move rapidly around and around"],["noun","a rapid rotation"]],
  "g1-u08-delighted": [["adjective","feeling great pleasure"]],
  "g1-u08-grateful": [["adjective","feeling or showing thanks"]],
  "g1-u08-groan": [["verb","make a deep sound expressing pain or sorrow"]],
  "g1-u08-mischief": [["noun","playfully troublesome behavior"]],
  "g1-u08-romp": [["verb","play energetically and noisily"]],
  "g1-u08-selfish": [["adjective","caring only about oneself"]],
  "g1-u08-splendid": [["adjective","very impressive and beautiful"]],
  "g1-u08-sprinkle": [["verb","scatter small drops or particles"]],
  "g1-u08-stormy": [["adjective","characterized by strong winds or rain"]],
  "g1-u08-stun": [["verb","render unconscious or dizzy"],["verb","astonish or shock"]],
  "g1-u09-attach": [["verb","join or fasten onto"]],
  "g1-u09-complete": [["verb","finish making or doing"],["adjective","having all necessary parts"]],
  "g1-u09-create": [["verb","bring into existence"]],
  "g1-u09-dainty": [["adjective","delicately small and pretty"]],
  "g1-u09-damage": [["verb","inflict harm on"],["noun","harm done"]],
  "g1-u09-edge": [["noun","the outer side or limit"],["noun","the sharp part of a blade"]],
  "g1-u09-jealous": [["adjective","envyingly vigilant"],["adjective","feeling resentful of someone's advantage"]],
  "g1-u09-misty": [["adjective","covered in mist"]],
  "g1-u09-roam": [["verb","travel or wander aimlessly"]],
  "g1-u09-silent": [["adjective","not making or accompanied by sound"]],
  "g1-u10-anxious": [["adjective","feeling or showing worry or nervousness"]],
  "g1-u10-creak": [["verb","make a harsh squeaking sound"]],
  "g1-u10-drowsy": [["adjective","sleepy"]],
  "g1-u10-exchange": [["verb","give something and receive something"],["noun","an act of swapping"]],
  "g1-u10-limp": [["adjective","not stiff or firm"],["verb","walk with difficulty"]],
  "g1-u10-plead": [["verb","make an emotional appeal"],["verb","state formally in a court"]],
  "g1-u10-polite": [["adjective","having or showing good manners"]],
  "g1-u10-trust": [["verb","believe in the reliability of"],["noun","firm belief in reliability"]],
  "g1-u10-whimper": [["verb","make low, feeble sounds expressive of fear or pain"]],
  "g1-u11-celebrate": [["verb","mark a special occasion with joy"]],
  "g1-u11-comfort": [["verb","make feel less sorrowful"],["noun","physical ease"]],
  "g1-u11-destroy": [["verb","put an end to the existence of by damaging"]],
  "g1-u11-injury": [["noun","physical harm caused to the body"]],
  "g1-u11-monument": [["noun","a statue or structure built to honor a person or event"]],
  "g1-u11-polish": [["verb","make smooth and shiny by rubbing"],["noun","substance used for polishing"]],
  "g1-u11-rescue": [["verb","save from danger or distress"]],
  "g1-u11-seek": [["verb","attempt to find or obtain"]],
  "g1-u11-symbol": [["noun","a thing that represents or stands for something else"]],
  "g1-u11-tidy": [["adjective","neat and arranged"],["verb","make neat"]],
  "g1-u12-argue": [["verb","give reasons for or against something"],["verb","quarrel or disagree"]],
  "g1-u12-clutch": [["verb","grasp tightly"],["noun","a tight grasp"]],
  "g1-u12-exhausted": [["adjective","completely worn out; very tired"]],
  "g1-u12-furious": [["adjective","extremely angry"]],
  "g1-u12-gently": [["adverb","in a mild, kind way"]],
  "g1-u12-journey": [["noun","an act of traveling from one place to another"]],
  "g1-u12-loosen": [["verb","make less tight"]],
  "g1-u12-remove": [["verb","take away or off"]],
  "g1-u12-traveler": [["noun","a person who travels"]],
  "g1-u12-wrap": [["verb","cover or enclose completely with paper or cloth"]],
  "g2-u01-branch": [["noun","a part of a tree that grows from the trunk"],["noun","a subdivision of a larger organization"]],
  "g2-u01-brave": [["adjective","willing to face danger"]],
  "g2-u01-dash": [["verb","move quickly and suddenly"],["noun","a short quick movement"]],
  "g2-u01-greedy": [["adjective","having an excessive desire for something"]],
  "g2-u01-pass": [["verb","move past"],["verb","give to someone"],["noun","an act of moving past"]],
  "g2-u01-present": [["adjective","existing or happening now"],["noun","a gift"],["verb","formally introduce"]],
  "g2-u01-stream": [["noun","a small river"],["verb","flow continuously"]],
  "g2-u01-trail": [["noun","a path through country or forest"],["verb","follow behind"]],
  "g2-u01-wise": [["adjective","having good judgment and experience"]],
  "g2-u02-bench": [["noun","a long seat for several people"]],
  "g2-u02-bridge": [["noun","a structure carrying a path over an obstacle"]],
  "g2-u02-cross": [["verb","go across"],["adjective","bad-tempered and annoyed"],["noun","a mark formed by two intersecting lines"]],
  "g2-u02-deep": [["adjective","extending a long way down or in"],["adjective","intense or profound"]],
  "g2-u02-fresh": [["adjective","new or different"],["adjective","not stale or spoiled"]],
  "g2-u02-frown": [["verb","wrinkle one's brow showing displeasure"]],
  "g2-u02-signal": [["noun","a gesture or sound conveying information"],["verb","indicate with a signal"]],
  "g2-u02-travel": [["verb","make a journey"]],
  "g2-u02-worry": [["verb","feel or cause to feel anxious"]],
  "g2-u03-beach": [["noun","a sandy shore at the edge of water"]],
  "g2-u03-center": [["noun","the middle point"],["noun","a place where activities are concentrated"]],
  "g2-u03-finally": [["adverb","eventually or in conclusion"]],
  "g2-u03-ocean": [["noun","the vast expanse of salt water covering most of the Earth"]],
  "g2-u03-wave": [["noun","a moving ridge of water on the sea"],["verb","move one's hand to greet or signal"]],
  "g2-u03-wonder": [["verb","feel curiosity about"],["noun","something that inspires awe"]],
  "g2-u04-arrive": [["verb","reach a destination"]],
  "g2-u04-clear": [["adjective","easy to understand or see"],["verb","remove obstructions"]],
  "g2-u04-enormous": [["adjective","very large in size or extent"]],
  "g2-u04-exactly": [["adverb","precisely"]],
  "g2-u04-float": [["verb","rest or move on the surface of water"]],
  "g2-u04-midnight": [["noun","twelve o'clock in the middle of the night"]],
  "g2-u04-rainbow": [["noun","an arch of colors formed in the sky"]],
  "g2-u04-snowstorm": [["noun","a heavy fall of snow accompanied by strong winds"]],
  "g2-u04-weekend": [["noun","Saturday and Sunday"]],
  "g2-u04-whisper": [["verb","speak very softly"]],
  "g2-u05-bright": [["adjective","full of light"],["adjective","intelligent and quick-witted"]],
  "g2-u05-chew": [["verb","bite and grind with the teeth"]],
  "g2-u05-flour": [["noun","a powder made from ground grain used in baking"]],
  "g2-u05-forest": [["noun","a large area covered with trees"]],
  "g2-u05-hour": [["noun","a period of sixty minutes"]],
  "g2-u05-inn": [["noun","an establishment providing lodging and food"]],
  "g2-u05-island": [["noun","a piece of land surrounded by water"]],
  "g2-u05-nibble": [["verb","take small bites"]],
  "g2-u05-pale": [["adjective","light in color"],["adjective","lacking intensity of color"]],
  "g2-u05-warn": [["verb","give notice of danger"]],
  "g2-u06-agree": [["verb","have the same opinion"]],
  "g2-u06-bare": [["adjective","not covered or clothed"]],
  "g2-u06-famous": [["adjective","known about by many people"]],
  "g2-u06-feast": [["noun","a large meal"],["verb","eat heartily"]],
  "g2-u06-gentle": [["adjective","having or showing a kind temperament"]],
  "g2-u06-hero": [["noun","a person admired for courage or noble qualities"]],
  "g2-u06-leader": [["noun","a person who leads a group"]],
  "g2-u06-notice": [["verb","become aware of"],["noun","a written announcement"]],
  "g2-u06-search": [["verb","try to find something"],["noun","an act of searching"]],
  "g2-u06-weak": [["adjective","lacking strength or power"]],
  "g2-u07-alarm": [["noun","a device that warns of danger"],["verb","frighten or disturb"]],
  "g2-u07-collect": [["verb","gather together"],["verb","request payment"]],
  "g2-u07-damp": [["adjective","slightly wet"]],
  "g2-u07-insect": [["noun","a small creature with six legs, e.g. bee or ant"]],
  "g2-u07-plant": [["noun","a living organism that grows in soil"],["verb","put a seed in the ground to grow"]],
  "g2-u07-safe": [["adjective","protected from danger or harm"]],
  "g2-u07-scatter": [["verb","throw or drop things in different directions"]],
  "g2-u07-soil": [["noun","the upper layer of earth in which plants grow"]],
  "g2-u07-team": [["noun","a group of people working together"]],
  "g2-u07-tool": [["noun","a device used to carry out a particular function"]],
  "g2-u08-dive": [["verb","plunge headfirst into water"],["noun","a headlong plunge"]],
  "g2-u08-enemy": [["noun","a person who is actively hostile to another"]],
  "g2-u08-frighten": [["verb","make afraid"]],
  "g2-u08-herd": [["noun","a large group of animals"],["verb","drive animals in a group"]],
  "g2-u08-pack": [["noun","a group of wolves or dogs"],["verb","fill tightly"]],
  "g2-u08-prove": [["verb","demonstrate the truth of"]],
  "g2-u08-seal": [["noun","a marine mammal"],["verb","close securely"]],
  "g2-u08-smooth": [["adjective","having an even surface"],["verb","make smooth"]],
  "g2-u08-soar": [["verb","fly or rise high in the air"]],
  "g2-u08-steady": [["adjective","firmly fixed and not shaky"]],
  "g2-u09-calm": [["adjective","peaceful and undisturbed"],["verb","make calm"]],
  "g2-u09-cheer": [["verb","shout encouragingly"],["noun","a shout of encouragement"]],
  "g2-u09-dawn": [["noun","the first light of day"]],
  "g2-u09-entire": [["adjective","whole"]],
  "g2-u09-fair": [["adjective","treating everyone equally"],["noun","a public event for entertainment or trade"]],
  "g2-u09-field": [["noun","an area of land used for a particular purpose"],["noun","a subject of study or area of activity"]],
  "g2-u09-harm": [["noun","physical damage or injury"],["verb","do harm to"]],
  "g2-u09-pain": [["noun","a strongly unpleasant physical sensation"],["verb","cause pain to"]],
  "g2-u09-shiver": [["verb","shake slightly from cold or fear"],["noun","a trembling motion"]],
  "g2-u09-tremble": [["verb","shake involuntarily"]],
  "g2-u10-board": [["noun","a long flat piece of wood"],["verb","enter a ship or airplane"],["noun","a group of people managing an organization"]],
  "g2-u10-curious": [["adjective","eager to learn or know about something"]],
  "g2-u10-dangerous": [["adjective","able or likely to cause harm"]],
  "g2-u10-doubt": [["verb","feel uncertain about"],["noun","a feeling of uncertainty"]],
  "g2-u10-eager": [["adjective","keenly interested"]],
  "g2-u10-fear": [["noun","an unpleasant emotion caused by the belief that something bad will happen"],["verb","be afraid of"]],
  "g2-u10-leap": [["verb","jump or spring forward"],["noun","a long jump"]],
  "g2-u10-screech": [["verb","make a loud harsh cry"]],
  "g2-u10-squeeze": [["verb","press firmly from opposite sides"]],
  "g2-u10-village": [["noun","a group of houses and associated buildings, larger than a hamlet"]],
  "g2-u11-beam": [["noun","a long sturdy piece of wood or metal"],["verb","smile radiantly"]],
  "g2-u11-carve": [["verb","cut out a shape from wood or stone"]],
  "g2-u11-den": [["noun","the home of a wild animal"],["noun","a small cozy room"]],
  "g2-u11-lean": [["verb","bend or slant in a particular direction"],["adjective","thin"]],
  "g2-u11-odd": [["adjective","different from what is usual or expected"],["adjective","not even or divisible by two"]],
  "g2-u11-proper": [["adjective","correct or suitable for circumstances"]],
  "g2-u11-scrape": [["verb","rub a hard object against a surface"],["noun","a mark caused by scraping"]],
  "g2-u11-steer": [["verb","guide the direction of a vehicle"]],
  "g2-u11-tender": [["adjective","gentle and kind"],["adjective","soft and easy to chew"]],
  "g2-u11-tense": [["adjective","feeling nervous and unable to relax"],["adjective","stretched tight"]],
  "g2-u12-escape": [["verb","get free"],["noun","an act of escaping"]],
  "g2-u12-honest": [["adjective","free of deceit"]],
  "g2-u12-label": [["noun","a piece of paper or cloth attached to an object giving information about it"],["verb","attach a label to"]],
  "g2-u12-modern": [["adjective","relating to the present or recent times"]],
  "g2-u12-object": [["noun","a material thing that can be seen and touched"],["verb","express disapproval"]],
  "g2-u12-pitch": [["verb","throw or set up"],["noun","the degree of highness or lowness of a sound"]],
  "g2-u12-select": [["verb","choose carefully"],["adjective","carefully chosen"]],
  "g2-u12-sniff": [["verb","breathe in through the nose to smell something"]],
  "g2-u12-stable": [["adjective","firmly established and unlikely to change"],["noun","a building where livestock is kept"]],
  "g2-u12-steep": [["adjective","rising or falling sharply"]],
  "g2-u13-accept": [["verb","consent to receive or undertake"]],
  "g2-u13-address": [["noun","the details of where someone lives"],["verb","speak to"],["verb","deal with a problem"]],
  "g2-u13-difficult": [["adjective","needing much effort or skill to accomplish"]],
  "g2-u13-excuse": [["noun","a reason given to justify a fault"],["verb","forgive or overlook"]],
  "g2-u13-expert": [["noun","a person with a high level of skill in a field"],["adjective","showing great knowledge or skill"]],
  "g2-u13-hollow": [["adjective","having a hole or empty space inside"]],
  "g2-u13-relax": [["verb","become less tense"],["verb","cause to become less tense"]],
  "g2-u13-section": [["noun","a distinct part of something"]],
  "g2-u13-stamp": [["noun","a small piece of paper used for postage"],["verb","press down hard"]],
  "g2-u13-whole": [["adjective","entire"],["noun","the entire thing"]],
  "g2-u14-admire": [["verb","regard with respect and pleasure"]],
  "g2-u14-handle": [["verb","deal with or control"],["noun","a part designed for holding"]],
  "g2-u14-major": [["adjective","important or large"],["noun","a main subject of study"]],
  "g2-u14-passenger": [["noun","a person traveling in a vehicle"]],
  "g2-u14-prepare": [["verb","make ready for use or consideration"]],
  "g2-u14-separate": [["verb","set apart"],["adjective","forming a unit by itself"]],
  "g2-u14-similar": [["adjective","resembling without being identical"]],
  "g2-u14-slender": [["adjective","gracefully thin"]],
  "g2-u14-task": [["noun","a piece of work to be done"]],
  "g3-u01-allow": [["verb","let have or do"]],
  "g3-u01-bitter": [["adjective","having a sharp unpleasant taste"],["adjective","filled with resentment"]],
  "g3-u01-common": [["adjective","occurring often or shared by many"]],
  "g3-u01-faint": [["adjective","weak and dizzy"],["adjective","very slight"]],
  "g3-u01-firm": [["adjective","strongly felt or securely in place"]],
  "g3-u01-force": [["verb","make someone do something against their will"]],
  "g3-u01-goal": [["noun","the object of a person's ambition or effort"]],
  "g3-u01-patient": [["adjective","able to endure delay or trouble calmly"],["noun","a person receiving medical treatment"]],
  "g3-u01-prefer": [["verb","like better"]],
  "g3-u01-trace": [["noun","a mark left behind"],["verb","find or discover"]],
  "g3-u02-aim": [["noun","a purpose or intention"],["verb","point toward a target"]],
  "g3-u02-aware": [["adjective","having knowledge of something"]],
  "g3-u02-defeat": [["verb","win a victory over"],["noun","a failure to win"]],
  "g3-u02-drift": [["verb","move without control"],["verb","be carried along by currents"]],
  "g3-u02-mild": [["adjective","gentle and not extreme"]],
  "g3-u02-pause": [["verb","stop briefly"],["noun","a temporary stop"]],
  "g3-u02-refuse": [["verb","indicate unwillingness"]],
  "g3-u02-route": [["noun","a way or course taken"]],
  "g3-u02-ruin": [["verb","destroy or spoil"],["noun","the remains of something destroyed"]],
  "g3-u02-solid": [["adjective","firm and stable"],["adjective","not hollow"]],
  "g3-u03-active": [["adjective","engaged in vigorous activity"]],
  "g3-u03-bargain": [["noun","an agreement between two people"],["verb","negotiate terms"]],
  "g3-u03-gasp": [["verb","breathe in suddenly with open mouth"]],
  "g3-u03-loyal": [["adjective","giving firm support to a person or cause"]],
  "g3-u03-resource": [["noun","a supply of something useful"],["noun","the ability to cope effectively"]],
  "g3-u03-sensitive": [["adjective","easily affected by external conditions"],["adjective","quick to detect or respond to change"]],
  "g3-u03-struggle": [["verb","make efforts to get free or overcome difficulty"],["noun","a fight or effort"]],
  "g3-u03-value": [["noun","the importance or worth of something"],["verb","hold in high regard"]],
  "g3-u03-vary": [["verb","change or differ"]],
  "g3-u03-wander": [["verb","move about aimlessly"]],
  "g3-u04-capture": [["verb","take by force or trickery"],["noun","an act of capturing"]],
  "g3-u04-coward": [["noun","a person who lacks courage"]],
  "g3-u04-exclaim": [["verb","cry out suddenly"]],
  "g3-u04-gloomy": [["adjective","dark or poorly lit"],["adjective","causing or feeling depression"]],
  "g3-u04-insist": [["verb","demand that something happens or is true"]],
  "g3-u04-passage": [["noun","a narrow way allowing passage"],["noun","a short section of a written work"]],
  "g3-u04-restless": [["adjective","unable to rest as a result of anxiety"]],
  "g3-u04-shallow": [["adjective","of little depth"],["adjective","lacking intellectual depth"]],
  "g3-u04-shatter": [["verb","break or cause to break into pieces"]],
  "g3-u04-talent": [["noun","natural aptitude or skill"]],
  "g3-u05-atmosphere": [["noun","the layer of gas surrounding the Earth"],["noun","the character of a place or situation"]],
  "g3-u05-brilliant": [["adjective","very bright"],["adjective","extremely intelligent or impressive"]],
  "g3-u05-convince": [["verb","persuade someone to do or believe something"]],
  "g3-u05-endure": [["verb","suffer patiently"],["verb","remain in existence"]],
  "g3-u05-glance": [["verb","take a quick look"],["noun","a quick look"]],
  "g3-u05-harsh": [["adjective","unpleasantly rough or severe"]],
  "g3-u05-plunge": [["verb","jump or dive quickly into water"],["noun","a sudden quick movement"]],
  "g3-u05-precious": [["adjective","of great value"],["adjective","beloved"]],
  "g3-u05-swift": [["adjective","happening quickly"]],
  "g3-u05-unite": [["verb","come together as one"]],
  "g3-u06-border": [["noun","a line separating two countries or areas"],["verb","be situated adjacent to"]],
  "g3-u06-certain": [["adjective","known for sure"],["adjective","particular but unspecified"]],
  "g3-u06-clasp": [["verb","hold firmly"],["noun","a device used for fastening"]],
  "g3-u06-depart": [["verb","leave especially to start a journey"]],
  "g3-u06-fierce": [["adjective","very forceful or powerful"],["adjective","violent or hostile"]],
  "g3-u06-journey": [["noun","an act of traveling from one place to another"]],
  "g3-u06-observe": [["verb","notice or perceive"],["verb","fulfill or respect"]],
  "g3-u06-superb": [["adjective","excellent or magnificent"]],
  "g3-u06-treasure": [["noun","a quantity of precious metals or gems"],["verb","value highly"]],
  "g3-u06-wisdom": [["noun","the quality of having good judgment"]],
  "g3-u07-accuse": [["verb","say that someone has committed an offense"]],
  "g3-u07-clever": [["adjective","quick to understand or learn"]],
  "g3-u07-coast": [["noun","the part of land adjacent to the sea"],["verb","move smoothly without much effort"]],
  "g3-u07-delicate": [["adjective","easily broken or damaged"],["adjective","requiring careful handling"]],
  "g3-u07-explore": [["verb","travel in or through an unfamiliar area"],["verb","investigate thoroughly"]],
  "g3-u07-imitate": [["verb","copy the behavior or appearance of"]],
  "g3-u07-pierce": [["verb","make a hole in"],["verb","sound sharply through"]],
  "g3-u07-rare": [["adjective","not found in large quantities or often"]],
  "g3-u07-symbol": [["noun","a thing that represents something else"]],
  "g3-u07-triumph": [["noun","a great victory or achievement"],["verb","achieve success"]],
  "g3-u08-ancient": [["adjective","belonging to the very distant past"]],
  "g3-u08-climate": [["noun","the average weather conditions of a place"],["noun","the prevailing attitudes of a group"]],
  "g3-u08-cling": [["verb","hold on tightly"]],
  "g3-u08-custom": [["noun","a traditional way of behaving"],["noun","the official department that administers duties"]],
  "g3-u08-decay": [["verb","become gradually worse"],["noun","the process of decaying"]],
  "g3-u08-disturb": [["verb","interrupt or interfere with"],["verb","make feel anxious"]],
  "g3-u08-expose": [["verb","make visible"],["verb","subject to danger"]],
  "g3-u08-perform": [["verb","carry out an action"],["verb","entertain an audience"]],
  "g3-u08-remote": [["adjective","situated far from major settlements"],["adjective","operated from distance"]],
  "g3-u08-timid": [["adjective","showing a lack of courage"]],
  "g3-u09-ability": [["noun","possession of the qualities or skills required for a particular task"]],
  "g3-u09-avoid": [["verb","keep away from or stop oneself from doing"]],
  "g3-u09-bashful": [["adjective","reluctant to draw attention to oneself; shy"]],
  "g3-u09-brief": [["adjective","lasting a short time"],["adjective","concise"]],
  "g3-u09-compete": [["verb","strive to gain or win something"]],
  "g3-u09-consider": [["verb","think carefully about"],["verb","take into account"]],
  "g3-u09-delightful": [["adjective","causing great pleasure"]],
  "g3-u09-honor": [["noun","great respect"],["verb","regard with great respect"]],
  "g3-u09-reflex": [["noun","an involuntary muscle action caused by a stimulus"]],
  "g3-u09-remark": [["verb","say something as a comment"],["noun","a comment"]],
  "g3-u10-actual": [["adjective","existing in fact; real"]],
  "g3-u10-brink": [["noun","the edge of a steep place or of something hazardous"]],
  "g3-u10-chill": [["noun","a feeling of cold"],["verb","make or become cold"],["adjective","relaxed"]],
  "g3-u10-conquer": [["verb","overcome or subjugate"],["verb","succeed in controlling"]],
  "g3-u10-fortunate": [["adjective","favored by luck"]],
  "g3-u10-fury": [["noun","wild or violent anger"]],
  "g3-u10-intend": [["verb","plan or mean to do something"]],
  "g3-u10-pattern": [["noun","a repeated decorative design"],["noun","a regular way in which something happens"]],
  "g3-u10-vibrant": [["adjective","full of energy and life"]],
  "g3-u10-wit": [["noun","the ability to use words cleverly and amusingly"],["noun","intelligence"]],
  "g3-u11-approach": [["verb","come near to"],["noun","a way of dealing with a situation"]],
  "g3-u11-approve": [["verb","officially agree to or accept as satisfactory"]],
  "g3-u11-glory": [["noun","great honor or praise"],["noun","splendor or beauty"]],
  "g3-u11-magnificent": [["adjective","extremely beautiful or impressive"]],
  "g3-u11-meek": [["adjective","quietly gentle and willing to obey"]],
  "g3-u11-prompt": [["adjective","arriving or happening without delay"],["verb","cause to take action"]],
  "g3-u11-revive": [["verb","restore to life or consciousness"],["verb","make active or healthy again"]],
  "g3-u11-tradition": [["noun","a custom or belief passed down from generation to generation"]],
  "g3-u11-watchful": [["adjective","watching carefully"]],
  "g3-u11-wreckage": [["noun","the remains of something that has been destroyed"]],
  "g3-u12-audible": [["adjective","able to be heard"]],
  "g3-u12-consume": [["verb","eat, drink or use up"],["verb","destroy completely"]],
  "g3-u12-glide": [["verb","move with a smooth continuous motion"]],
  "g3-u12-origin": [["noun","the beginning or something from which something arises"]],
  "g3-u12-prevent": [["verb","stop from happening"]],
  "g3-u12-punctuate": [["verb","put punctuation marks in"],["verb","interrupt at intervals"]],
  "g3-u12-representative": [["noun","a person chosen to act or speak for others"],["adjective","typical"]],
  "g3-u12-scorn": [["noun","a feeling of contempt"],["verb","reject with contempt"]],
  "g3-u12-stout": [["adjective","rather fat"],["adjective","strong and thick"]],
  "g3-u12-woe": [["noun","great sorrow or distress"]],
  "g3-u13-arch": [["noun","a curved structure supporting the weight of what is above it"],["adjective","principal"]],
  "g3-u13-authentic": [["adjective","of undisputed origin; genuine"]],
  "g3-u13-clarify": [["verb","make clear or easy to understand"]],
  "g3-u13-declare": [["verb","say something solemnly or officially"]],
  "g3-u13-grant": [["verb","give or allow"],["noun","a sum of money given by an organization"]],
  "g3-u13-grave": [["adjective","giving cause for alarm; serious"],["noun","a place of burial"]],
  "g3-u13-modest": [["adjective","unassuming in the estimation of one's abilities"],["adjective","small in amount"]],
  "g3-u13-opponent": [["noun","a person who competes with or opposes another"]],
  "g3-u13-valid": [["adjective","able to be used or accepted because it meets requirements"]],
  "g3-u13-yearn": [["verb","have a strong longing"]],
  "g3-u14-admirable": [["adjective","deserving respect"]],
  "g3-u14-automatic": [["adjective","done or working without human control or intervention"]],
  "g3-u14-devotion": [["noun","love, loyalty, or enthusiasm for a person or activity"]],
  "g3-u14-distant": [["adjective","far away in space or time"],["adjective","not friendly or warm"]],
  "g3-u14-dreary": [["adjective","depressingly dull"]],
  "g3-u14-exhaust": [["verb","use up completely"],["verb","tire out"],["noun","waste gases from an engine"]],
  "g3-u14-kindle": [["verb","light or set on fire"],["verb","arouse or inspire"]],
  "g3-u14-predict": [["verb","say that something will happen in the future"]],
  "g3-u14-separation": [["noun","the action of separating"],["noun","the state of being separate"]],
  "g3-u14-stunt": [["noun","an action displaying spectacular skill"],["verb","prevent from growing or developing"]],
  "g3-u15-abundant": [["adjective","existing in large quantities"]],
  "g3-u15-barrier": [["noun","a fence or blockade that blocks movement"],["noun","a circumstance that prevents progress"]],
  "g3-u15-conceive": [["verb","form an idea in mind"],["verb","become pregnant"]],
  "g3-u15-formal": [["adjective","following customary rules"],["adjective","official"]],
  "g3-u15-inquire": [["verb","ask for information"]],
  "g3-u15-penalize": [["verb","impose a penalty on"]],
  "g3-u15-picturesque": [["adjective","visually attractive"]],
  "g3-u15-predator": [["noun","an animal that hunts and kills others"],["noun","a person who exploits others"]],
  "g3-u15-privilege": [["noun","a special advantage or right granted to a particular group"]],
  "g3-u15-slumber": [["verb","sleep"],["noun","sleep"]],
  "g3-u16-advantage": [["noun","a favorable circumstance"],["verb","make use of"]],
  "g3-u16-ambition": [["noun","a strong desire to achieve something"],["noun","determination to succeed"]],
  "g3-u16-defiant": [["adjective","showing open resistance"]],
  "g3-u16-fearsome": [["adjective","causing fear"]],
  "g3-u16-imply": [["verb","strongly suggest the truth or existence of something"]],
  "g3-u16-merit": [["noun","the quality of being particularly good or worthy"],["verb","deserve"]],
  "g3-u16-negotiate": [["verb","discuss something to reach an agreement"],["verb","successfully get through"]],
  "g3-u16-purify": [["verb","remove contaminants from"]],
  "g3-u16-revoke": [["verb","officially cancel or withdraw"]],
  "g3-u16-wretched": [["adjective","of very poor quality; miserable"]],
  "g3-u17-absorb": [["verb","take in or soak up"],["verb","engross completely"]],
  "g3-u17-amateur": [["noun","a person who does something without professional qualifications"],["adjective","not professional"]],
  "g3-u17-channel": [["noun","a passage for water or broadcast"],["verb","direct or guide"]],
  "g3-u17-elegant": [["adjective","graceful and stylish"]],
  "g3-u17-grace": [["noun","smoothness and elegance of movement"],["noun","courteous good will"]],
  "g3-u17-inspect": [["verb","look at closely and critically"]],
  "g3-u17-lame": [["adjective","unable to walk properly"],["adjective","foolish and ineffective"]],
  "g3-u17-suspend": [["verb","temporarily prevent from working"],["verb","hang from above"]],
  "g3-u17-tiresome": [["adjective","causing one to feel bored or annoyed"]],
  "g3-u17-tranquil": [["adjective","free from disturbance"]],
  "g3-u18-boast": [["verb","talk with excessive pride"],["noun","an act of boasting"]],
  "g3-u18-eloquent": [["adjective","fluent or persuasive in speaking or writing"]],
  "g3-u18-glisten": [["verb","shine with a reflected light"]],
  "g3-u18-ideal": [["adjective","satisfying one's conception of perfection"],["noun","a standard of perfection"]],
  "g3-u18-infectious": [["adjective","likely to spread or influence others"],["adjective","transmitted by infection"]],
  "g3-u18-invest": [["verb","expend money with expectation of profit"],["verb","dedicate time or effort"]],
  "g3-u18-locate": [["verb","discover the exact place of"],["verb","establish in a particular place"]],
  "g3-u18-ripple": [["noun","a small wave"],["verb","form into ripples"]],
  "g3-u18-sufficient": [["adjective","enough"]],
  "g3-u18-uproar": [["noun","a noisy disturbance"]],
  "g4-u01-celebrity": [["noun","a famous person"]],
  "g4-u01-counsel": [["noun","advice or guidance"],["verb","advise"]],
  "g4-u01-demonstrate": [["verb","clearly show the truth of"],["verb","take part in a public protest"]],
  "g4-u01-essential": [["adjective","absolutely necessary"],["noun","an essential thing"]],
  "g4-u01-hardship": [["noun","severe suffering or privation"]],
  "g4-u01-haul": [["verb","pull or drag with effort"],["noun","the amount of something gained"]],
  "g4-u01-humble": [["adjective","showing modest or low estimate of one's importance"],["verb","lower the dignity of"]],
  "g4-u01-pledge": [["noun","a solemn promise"],["verb","commit oneself"]],
  "g4-u01-sincere": [["adjective","free of pretense"]],
  "g4-u01-stampede": [["noun","a sudden rush of animals or people"],["verb","rush wildly"]],
  "g4-u02-annual": [["adjective","occurring once every year"]],
  "g4-u02-basic": [["adjective","forming the base or foundation; fundamental"]],
  "g4-u02-competition": [["noun","activity of competing"],["noun","an event in which people compete"]],
  "g4-u02-contract": [["noun","a legally binding agreement"],["verb","decrease in size or number"]],
  "g4-u02-dismiss": [["verb","send away or remove from employment or consideration"]],
  "g4-u02-neglect": [["verb","pay no attention to"],["noun","lack of care"]],
  "g4-u02-obtain": [["verb","get, acquire, or secure"]],
  "g4-u02-portion": [["noun","a part or share"]],
  "g4-u02-recall": [["verb","remember"],["verb","officially order to return"]],
  "g4-u02-sponsor": [["noun","a person who gives financial support"],["verb","promote or support"]],
  "g4-u02-stern": [["adjective","severe or strict"],["noun","the back part of a ship"]],
  "g4-u02-vacant": [["adjective","not occupied; empty"]],
  "g4-u03-attractive": [["adjective","pleasing or appealing to look at or consider"]],
  "g4-u03-burden": [["noun","a heavy load"],["verb","weigh down with a burden"]],
  "g4-u03-consent": [["noun","permission for something to happen"],["verb","express willingness"]],
  "g4-u03-dependable": [["adjective","trustworthy and reliable"]],
  "g4-u03-indicate": [["verb","point out"],["verb","signify or suggest"]],
  "g4-u03-previous": [["adjective","existing or occurring before in time"]],
  "g4-u03-qualify": [["verb","meet the necessary conditions"],["verb","make less strong"]],
  "g4-u03-response": [["noun","an answer or reaction"]],
  "g4-u03-shabby": [["adjective","in poor condition"],["adjective","unfair"]],
  "g4-u03-thaw": [["verb","become liquid or soft as a result of warming"],["noun","a period of warmer weather"]],
  "g4-u03-urgent": [["adjective","requiring immediate action"]],
  "g4-u03-vanity": [["noun","excessive pride in one's appearance"],["noun","futileness"]],
  "g4-u04-ambush": [["noun","a surprise attack by people lying in wait"],["verb","make a surprise attack on"]],
  "g4-u04-calculate": [["verb","find the amount or number by using mathematical processes"]],
  "g4-u04-contribute": [["verb","give a part of one's ability or resources"],["verb","be one of the causes of"]],
  "g4-u04-dread": [["verb","anticipate with great fear or apprehension"],["noun","great fear or apprehension"]],
  "g4-u04-employ": [["verb","give work to"],["verb","make use of"]],
  "g4-u04-extend": [["verb","make longer or larger"],["verb","offer or present"]],
  "g4-u04-frantic": [["adjective","wildly excited or anxious"]],
  "g4-u04-initial": [["adjective","existing or occurring at the beginning"]],
  "g4-u04-routine": [["noun","a sequence of actions regularly followed"],["adjective","done as part of a regular procedure"]],
  "g4-u04-stun": [["verb","render unconscious or dizzy"],["verb","astonish"]],
  "g4-u04-sturdy": [["adjective","strong and robust"]],
  "g4-u04-yield": [["verb","produce"],["verb","surrender"],["noun","an amount produced"]],
  "g4-u05-antique": [["noun","a collectible object having considerable age"],["adjective","having value because of age"]],
  "g4-u05-baggage": [["noun","suitcases packed for traveling"],["noun","emotional issues carried over from the past"]],
  "g4-u05-digest": [["verb","break down food in the body"],["noun","a collection of articles"]],
  "g4-u05-establish": [["verb","set up on a firm basis"],["verb","prove the truth of"]],
  "g4-u05-external": [["adjective","situated or occurring outside"]],
  "g4-u05-haste": [["noun","excessive speed or urgency of movement"]],
  "g4-u05-humid": [["adjective","having a high degree of moisture"]],
  "g4-u05-lash": [["verb","beat with a whip"],["verb","strike forcefully"],["noun","the flexible part of a whip"]],
  "g4-u05-oppose": [["verb","resist or take action against"]],
  "g4-u05-pioneer": [["noun","a person who is among the first to do something"],["verb","develop or introduce"]],
  "g4-u05-sensible": [["adjective","showing good judgment"],["adjective","able to perceive"]],
  "g4-u05-worthy": [["adjective","deserving"]],
  "g4-u06-blossom": [["verb","produce flowers"],["noun","a flower or mass of flowers"]],
  "g4-u06-collide": [["verb","hit forcefully against"],["verb","come into conflict"]],
  "g4-u06-constant": [["adjective","occurring continuously over a period of time"],["adjective","remaining the same"]],
  "g4-u06-content": [["adjective","in a state of peaceful satisfaction"],["noun","something contained"],["verb","satisfy"]],
  "g4-u06-distract": [["verb","take attention away from something"]],
  "g4-u06-drought": [["noun","a prolonged period of abnormally low rainfall"]],
  "g4-u06-foul": [["adjective","offensive to the senses or immoral"],["verb","commit a foul in sport"],["noun","in sport, an unfair act"]],
  "g4-u06-noble": [["adjective","having or showing fine personal qualities"],["noun","a person of high social rank"]],
  "g4-u06-policy": [["noun","a course or principle of action adopted by an organization"]],
  "g4-u06-quiver": [["verb","shake slightly"],["noun","an instance of trembling"]],
  "g4-u06-slight": [["adjective","small in degree"],["verb","insult by treating as unimportant"]],
  "g4-u06-tidy": [["adjective","neat and ordered"],["verb","make tidy"]],
  "g4-u07-accurate": [["adjective","correct in all details"]],
  "g4-u07-alert": [["adjective","quick to notice any unusual and potentially dangerous event"],["verb","warn of a danger"],["noun","a state of watchfulness"]],
  "g4-u07-ancestor": [["noun","a person from whom one is descended"]],
  "g4-u07-disaster": [["noun","a sudden event causing great damage or misfortune"]],
  "g4-u07-elementary": [["adjective","relating to the basic elements"],["adjective","relating to primary school"]],
  "g4-u07-envy": [["noun","a feeling of discontented longing with regard to someone else's possessions"],["verb","desire to have qualities or possessions of"]],
  "g4-u07-epidemic": [["noun","a widespread occurrence of disease in a community"],["adjective","of the nature of an epidemic"]],
  "g4-u07-feeble": [["adjective","lacking physical strength"],["adjective","inadequate"]],
  "g4-u07-penetrate": [["verb","pierce or pass into or through"],["verb","gain access to"]],
  "g4-u07-romp": [["verb","play energetically and noisily"]],
  "g4-u07-staple": [["noun","a basic or essential thing"],["adjective","main or important"],["noun","a small paper clip used to hold papers"]],
  "g4-u07-survive": [["verb","continue to live or exist despite danger or hardship"]],
  "g4-u08-awkward": [["adjective","causing difficulty; hard to do or deal with"],["adjective","uncomfortable or shamefully embarrassing"]],
  "g4-u08-clatter": [["verb","move with a continuous rattling sound"],["noun","a continuous rattling sound"]],
  "g4-u08-gallant": [["adjective","brave"],["adjective","chivalrous"]],
  "g4-u08-lukewarm": [["adjective","moderately warm"],["adjective","showing little enthusiasm"]],
  "g4-u08-plentiful": [["adjective","existing in great quantities"]],
  "g4-u08-ration": [["noun","a fixed amount of something allotted to a person"],["verb","limit supplies"]],
  "g4-u08-reserve": [["verb","retain for future use"],["verb","book in advance"],["noun","a supply kept for future use"]],
  "g4-u08-scholar": [["noun","a specialist in a particular branch of study"],["noun","a student awarded a scholarship"]],
  "g4-u08-smolder": [["verb","burn slowly with smoke but no flame"]],
  "g4-u08-trudge": [["verb","walk slowly and with heavy steps"]],
  "g4-u08-volunteer": [["noun","a person who freely offers to undertake a task"],["verb","offer to do something"]],
  "g4-u08-weary": [["adjective","showing signs of tiredness"]],
  "g4-u09-convict": [["verb","declare to be guilty of a criminal offense"],["noun","a person found guilty"]],
  "g4-u09-discipline": [["noun","the practice of training people to obey rules"],["noun","a branch of knowledge"],["verb","train someone to obey rules"]],
  "g4-u09-dungeon": [["noun","a prison cell, typically underground"]],
  "g4-u09-earnest": [["adjective","serious and committed"]],
  "g4-u09-enclose": [["verb","surround or close off on all sides"],["verb","place something in an envelope with a letter"]],
  "g4-u09-gradual": [["adjective","occurring or developing slowly or by small increments"]],
  "g4-u09-grumble": [["verb","complain in a bad-tempered way"],["noun","a complaint"]],
  "g4-u09-jagged": [["adjective","having rough, sharp points protruding"]],
  "g4-u09-nourish": [["verb","provide with food necessary for growth"],["verb","keep (a feeling) alive"]],
  "g4-u09-provision": [["noun","the act of supplying"],["noun","a condition requiring future action"],["noun","supplies of food and drink"]],
  "g4-u09-treaty": [["noun","a formally concluded agreement between countries"]],
  "g4-u09-uneasy": [["adjective","causing or feeling anxiety"]],
  "g4-u10-distress": [["noun","extreme anxiety or sorrow"],["verb","cause great trouble or suffering to"]],
  "g4-u10-drench": [["verb","make completely wet"]],
  "g4-u10-dwell": [["verb","live in or at a specified place"]],
  "g4-u10-juvenile": [["adjective","of or relating to young people"],["noun","a young person"]],
  "g4-u10-outstanding": [["adjective","exceptionally good"],["adjective","not yet resolved or completed"]],
  "g4-u10-proceed": [["verb","continue after interruption"],["verb","begin a course of action"]],
  "g4-u10-register": [["verb","enter or record in an official list"],["noun","an official list or record"]],
  "g4-u10-sift": [["verb","separate or sort by a process"],["verb","examine carefully"]],
  "g4-u10-spree": [["noun","a short period of doing something to excess"]],
  "g4-u10-tardy": [["adjective","delayed; late"]],
  "g4-u10-unfit": [["adjective","not suitable for a particular purpose"]],
  "g4-u10-variety": [["noun","the quality of being diverse"],["noun","a thing differing from others of the same general class"]],
  "g4-u11-blockade": [["noun","an act of blocking"],["verb","obstruct with a blockade"]],
  "g4-u11-chant": [["noun","a repeated rhythmic phrase"],["verb","shout or sing repeatedly"]],
  "g4-u11-despair": [["noun","the complete loss or absence of hope"],["verb","lose hope"]],
  "g4-u11-elevate": [["verb","lift or raise"],["verb","raise to a more important position"]],
  "g4-u11-extraordinary": [["adjective","very unusual or remarkable"]],
  "g4-u11-heroic": [["adjective","showing extreme courage"],["adjective","of or like a hero"]],
  "g4-u11-lance": [["noun","a long weapon with a pointed head"]],
  "g4-u11-missionary": [["noun","a person sent to promote a religious doctrine in a foreign country"]],
  "g4-u11-pointless": [["adjective","having little or no sense, use, or purpose"]],
  "g4-u11-reflect": [["verb","think carefully about something"],["verb","throw back light or sound"]],
  "g4-u11-site": [["noun","a piece of land where something is or was located"]],
  "g4-u11-toxic": [["adjective","poisonous"]],
  "g4-u12-bristle": [["noun","a short stiff hair"],["verb","stand or move stiffly"],["verb","react angrily"]],
  "g4-u12-circular": [["adjective","having the form of a circle"],["adjective","moving in a cycle"]],
  "g4-u12-coarse": [["adjective","rough or loose in texture"],["adjective","unrefined or indecent"]],
  "g4-u12-discard": [["verb","get rid of something as no longer useful"]],
  "g4-u12-extreme": [["adjective","reaching a high or the highest degree"],["noun","either of two extreme points"]],
  "g4-u12-focus": [["verb","center attention on"],["noun","the center of interest or activity"]],
  "g4-u12-grasp": [["verb","seize firmly"],["verb","comprehend fully"],["noun","firm hold"]],
  "g4-u12-inspire": [["verb","fill someone with the urge or ability to do something"]],
  "g4-u12-magnify": [["verb","make appear larger"],["verb","overstate"]],
  "g4-u12-marine": [["adjective","relating to the sea"],["noun","a member of a marine corps"]],
  "g4-u12-quake": [["verb","shake or tremble"],["noun","an earthquake"]],
  "g4-u12-troublesome": [["adjective","causing difficulty or problems"]],
  "g4-u13-abstract": [["adjective","existing in thought as an idea"],["adjective","difficult to understand"],["noun","a summary"]],
  "g4-u13-ally": [["noun","a person or organization that cooperates with others"],["verb","form an alliance with"]],
  "g4-u13-appoint": [["verb","assign a job or role to someone"]],
  "g4-u13-attentive": [["adjective","paying close attention"],["adjective","considerate"]],
  "g4-u13-bonus": [["noun","an extra payment added to the basic salary"],["noun","something given as a reward"]],
  "g4-u13-carefree": [["adjective","free from anxiety or responsibility"]],
  "g4-u13-courtesy": [["noun","the showing of politeness"],["adjective","provided free of charge as a favor"]],
  "g4-u13-manufacture": [["verb","make something on a large scale using machinery"],["noun","the making of goods in large quantities"]],
  "g4-u13-mistrust": [["noun","lack of trust"],["verb","feel no trust in"]],
  "g4-u13-noticeable": [["adjective","easily seen or noticed"]],
  "g4-u13-overthrow": [["verb","remove forcibly from power"],["noun","a removal from power"]],
  "g4-u13-peculiar": [["adjective","strange or odd"],["adjective","particular to one person or group"]],
  "g4-u14-absolute": [["adjective","total and complete"],["adjective","not limited"]],
  "g4-u14-arena": [["noun","a level area for sporting events or performances"],["noun","an area of activity"]],
  "g4-u14-compliment": [["noun","a polite expression of praise"],["verb","politely congratulate or praise"]],
  "g4-u14-deliberate": [["adjective","done on purpose"],["adjective","slow and careful"],["verb","think carefully"]],
  "g4-u14-dense": [["adjective","closely compacted"],["adjective","stupid"]],
  "g4-u14-dominant": [["adjective","having power or influence over others"],["adjective","most important"]],
  "g4-u14-hazardous": [["adjective","involving potential risk"],["adjective","dangerous"]],
  "g4-u14-necessity": [["noun","a thing that is needed"],["noun","the quality of being necessary"]],
  "g4-u14-offend": [["verb","fail to comply with law or rule"],["verb","cause to feel upset"]],
  "g4-u14-regain": [["verb","obtain again"],["verb","recover possession of"]],
  "g4-u14-thorough": [["adjective","complete with regard to every detail"]],
  "g4-u15-adopt": [["verb","legally take another's child as one's own"],["verb","choose to follow or use"]],
  "g4-u15-agile": [["adjective","able to move quickly and easily"],["adjective","able to think quickly"]],
  "g4-u15-analyze": [["verb","examine something in detail"]],
  "g4-u15-assist": [["verb","give help or support"]],
  "g4-u15-babble": [["verb","talk rapidly and continuously"],["verb","make continuous incomprehensible speech"]],
  "g4-u15-captivity": [["noun","the state of being imprisoned"]],
  "g4-u15-drab": [["adjective","dull and boring"],["adjective","without brightness"]],
  "g4-u15-fatal": [["adjective","causing death"],["adjective","disastrous"]],
  "g4-u15-generosity": [["noun","the quality of being generous"]],
  "g4-u15-genuine": [["adjective","truly what something is said to be"],["adjective","honest and sincere"]],
  "g4-u15-illegal": [["adjective","contrary to or forbidden by law"]],
  "g4-u17-impulse": [["noun","a sudden strong urge to do something"],["noun","a sudden powerful driving force"]],
  "g4-u17-interpret": [["verb","explain the meaning of"],["verb","translate one language into another"]],
  "g4-u17-orient": [["verb","determine the position of in relation to surroundings"],["verb","adapt to or familiarize with"],["adjective","relating to eastern countries"]],
  "g4-u17-sector": [["noun","an area or portion that is distinct from others"]],
  "g4-u17-submit": [["verb","accept an unpleasant situation"],["verb","present for consideration"]],
  "g4-u17-zest": [["noun","great enthusiasm and energy"]],
  "g4-u18-abide": [["verb","accept or obey a rule or decision"],["verb","continue"]],
  "g4-u18-contrast": [["noun","the state of being noticeably different"],["verb","compare so as to show differences"]],
  "g4-u18-depress": [["verb","sadden"],["verb","push down"],["verb","make less active"]],
  "g4-u18-dismal": [["adjective","causing a feeling of gloom or despondency"]],
  "g4-u18-dispose": [["verb","arrange in a particular position"],["verb","make willing to do something"]],
  "g4-u18-exaggerate": [["verb","represent something as larger or greater than it really is"]],
  "g4-u18-indifferent": [["adjective","not caring"],["adjective","neither good nor bad"]],
  "g4-u18-jubilant": [["adjective","feeling or expressing great happiness"]],
  "g4-u18-manual": [["adjective","relating to the hands"],["adjective","operated by hand"],["noun","a reference book"]],
  "g4-u18-originate": [["verb","begin to exist"],["verb","create or initiate"]],
  "g4-u18-recognition": [["noun","the action of recognizing"],["noun","acknowledgment of achievement"]],
  "g4-u18-tribute": [["noun","a gift made as an expression of gratitude"],["noun","evidence or acknowledgement"]],
  "g5-u01-blunder": [["noun","a stupid or careless mistake"],["verb","make a mistake"]],
  "g5-u01-cancel": [["verb","decide that a planned event will not happen"],["verb","revoke or annul"]],
  "g5-u01-continuous": [["adjective","without a break"]],
  "g5-u01-distribute": [["verb","share out among a number of recipients"],["verb","spread over an area"]],
  "g5-u01-document": [["noun","a written record of information"],["verb","record in writing"]],
  "g5-u01-fragile": [["adjective","easily broken or damaged"],["adjective","delicate"]],
  "g5-u01-myth": [["noun","a traditional story serving to explain some natural or social phenomenon"],["noun","a widely held but false belief"]],
  "g5-u01-reject": [["verb","dismiss as inadequate or unsuitable"],["verb","refuse to accept"],["noun","something rejected"]],
  "g5-u01-scuffle": [["noun","a short fight or confused struggle"],["verb","engage in a scuffle"]],
  "g5-u01-solitary": [["adjective","done or existing alone"],["adjective","lonely"]],
  "g5-u01-temporary": [["adjective","lasting only a short time"]],
  "g5-u01-veteran": [["noun","a person with long experience in a particular field"],["noun","a person who has served in the armed forces"]],
  "g5-u02-abandon": [["verb","give up completely"],["verb","desert"]],
  "g5-u02-assault": [["noun","a violent attack"],["verb","physically attack"]],
  "g5-u02-convert": [["verb","change in form, character, or function"],["verb","persuade to adopt a particular belief"],["noun","a person who has changed beliefs"]],
  "g5-u02-dispute": [["noun","a disagreement"],["verb","argue about something"],["verb","deny or contradict"]],
  "g5-u02-impressive": [["adjective","evoking admiration or respect"]],
  "g5-u02-justify": [["verb","show or prove to be just or reasonable"]],
  "g5-u02-misleading": [["adjective","giving the wrong impression"]],
  "g5-u02-numerous": [["adjective","great in number; many"]],
  "g5-u02-productive": [["adjective","producing much"],["adjective","producing good results"]],
  "g5-u02-shrewd": [["adjective","having or showing sharp powers of judgment"]],
  "g5-u02-strategy": [["noun","a plan of action designed to achieve a major aim"]],
  "g5-u02-villain": [["noun","a person responsible for particular bad deed"],["noun","a wicked person in literature"]],
  "g5-u03-bluff": [["verb","try to deceive someone by appearing confident"],["noun","an attempt to deceive"],["adjective","good-naturedly direct"]],
  "g5-u03-cautious": [["adjective","careful to avoid problems or danger"]],
  "g5-u03-consist": [["verb","be composed of"],["verb","depend on"]],
  "g5-u03-despise": [["verb","feel contempt for"]],
  "g5-u03-haven": [["noun","a place of safety or refuge"]],
  "g5-u03-miniature": [["adjective","very small of its kind"],["noun","a very small model or copy"]],
  "g5-u03-monarch": [["noun","a ruler, especially a king or queen"]],
  "g5-u03-obstacle": [["noun","a thing that blocks one's way or prevents progress"]],
  "g5-u03-postpone": [["verb","cause to happen at a later time"]],
  "g5-u03-straggle": [["verb","move along slowly in small groups"],["verb","be or become separated"]],
  "g5-u03-treacherous": [["adjective","not to be trusted"],["adjective","dangerous"]],
  "g5-u03-vivid": [["adjective","producing powerful feelings or images in the mind"],["adjective","very bright"]],
  "g5-u04-aggressive": [["adjective","ready to attack"],["adjective","showing determination and force"]],
  "g5-u04-associate": [["verb","connect (someone or something) with something else"],["verb","spend time socially"],["noun","a partner or companion"]],
  "g5-u04-deceive": [["verb","deliberately mislead"]],
  "g5-u04-emigrate": [["verb","leave one's country to settle permanently in another"]],
  "g5-u04-flexible": [["adjective","able to bend without breaking"],["adjective","able to adapt to change"]],
  "g5-u04-glamour": [["noun","the attractive or exciting quality of being special or ideal"]],
  "g5-u04-hazy": [["adjective","marked by a haze"],["adjective","vague or unclear"]],
  "g5-u04-linger": [["verb","stay somewhere longer than necessary"],["verb","continue to be felt or remembered"]],
  "g5-u04-luxurious": [["adjective","extremely comfortable and elegant"],["adjective","involving great expense"]],
  "g5-u04-mishap": [["noun","an unlucky accident"]],
  "g5-u04-overwhelm": [["verb","sweep over with force"],["verb","defeat or overcome"]],
  "g5-u04-span": [["noun","the length of time or period"],["noun","the full extent of something"],["verb","extend across"]],
  "g5-u05-blemish": [["noun","a small mark or flaw that spoils appearance"],["verb","spoil the appearance or character of"]],
  "g5-u05-blunt": [["adjective","not sharp"],["adjective","without a sharp edge or point"],["verb","make less sharp"],["adjective","without polite or diplomatic language"]],
  "g5-u05-capable": [["adjective","having ability or quality to do something"]],
  "g5-u05-conclude": [["verb","bring or come to an end"],["verb","arrive at a judgment after consideration"]],
  "g5-u05-detect": [["verb","discover or identify presence of"]],
  "g5-u05-fatigue": [["noun","extreme tiredness"],["verb","make tired"],["adjective","causing tiredness"]],
  "g5-u05-festive": [["adjective","relating to or characteristic of a festival"]],
  "g5-u05-hospitality": [["noun","the friendly reception and treatment of guests or strangers"]],
  "g5-u05-nomad": [["noun","a member of a community that lives by moving from place to place"]],
  "g5-u05-persecute": [["verb","subject to hostility and ill-treatment"],["verb","pester"]],
  "g5-u05-supreme": [["adjective","highest in rank or authority"],["adjective","greatest in power or degree"]],
  "g5-u05-transport": [["verb","take from one place to another in a vehicle"],["noun","a system for carrying passengers"]],
  "g5-u06-accomplish": [["verb","successfully complete or achieve"]],
  "g5-u06-apparent": [["adjective","clearly visible or understood"],["adjective","seeming real or true but not necessarily so"]],
  "g5-u06-capacity": [["noun","the maximum amount that can be held or accommodated"],["noun","ability or power"]],
  "g5-u06-civilian": [["noun","a person not in the armed services or police"],["adjective","relating to civilians"]],
  "g5-u06-conceal": [["verb","hide something"],["verb","prevent from being known"]],
  "g5-u06-duplicate": [["adjective","exactly like something else"],["noun","a copy"],["verb","make a copy of"]],
  "g5-u06-keen": [["adjective","eager or enthusiastic"],["adjective","sharp"]],
  "g5-u06-provoke": [["verb","stimulate or give rise to"],["verb","make angry"]],
  "g5-u06-spurt": [["verb","gush out suddenly"],["verb","move with a sudden burst of speed"],["noun","a sudden gush"]],
  "g5-u06-undoing": [["noun","the cause of someone's failure or ruin"]],
  "g5-u06-vast": [["adjective","extremely large in area or extent"]],
  "g5-u06-withdraw": [["verb","remove from or keep out of a particular place or position"],["verb","leave or retreat"]],
  "g5-u07-barrier": [["noun","a fence or blockade that blocks movement"],["noun","an obstacle"]],
  "g5-u07-calculate": [["verb","find the amount or number by using math"]],
  "g5-u07-compose": [["verb","write or create"],["verb","be constituted of"],["verb","calm oneself"]],
  "g5-u07-considerable": [["adjective","notably large in size or extent"]],
  "g5-u07-deputy": [["noun","a person appointed to act for another"]],
  "g5-u07-industrious": [["adjective","hardworking and diligent"]],
  "g5-u07-jolt": [["verb","shake or move with a sudden jerk"],["verb","surprise or shock"],["noun","a sudden movement"]],
  "g5-u07-loot": [["verb","steal goods from a place, typically during a war or riot"],["noun","goods stolen in this way"]],
  "g5-u07-rejoice": [["verb","feel great happiness"]],
  "g5-u07-reliable": [["adjective","consistently good in quality or performance; dependable"]],
  "g5-u07-senseless": [["adjective","lacking in meaning; nonsensical"]],
  "g5-u07-shrivel": [["verb","wrinkle and contract through loss of moisture"]],
  "g5-u08-alternate": [["verb","occur in turn repeatedly"],["verb","swap"],["adjective","every other"]],
  "g5-u08-demolish": [["verb","completely destroy"],["verb","refute a theory completely"]],
  "g5-u08-energetic": [["adjective","showing or involving great activity or vitality"]],
  "g5-u08-enforce": [["verb","make sure a law or rule is obeyed"],["verb","compel"]],
  "g5-u08-feat": [["noun","a heroic or impressive act"]],
  "g5-u08-hearty": [["adjective","showing warm and sincere feeling"],["adjective","large and satisfying"]],
  "g5-u08-mature": [["adjective","fully grown and developed"],["adjective","like an adult"],["verb","become mature"]],
  "g5-u08-observant": [["adjective","quick to notice things; attentive"]],
  "g5-u08-primary": [["adjective","most important"],["adjective","first in order or time"]],
  "g5-u08-resign": [["verb","voluntarily leave a job"],["verb","accept that something cannot be changed"]],
  "g5-u08-strive": [["verb","try hard to achieve something"]],
  "g5-u08-verdict": [["noun","a judgment or decision reached"],["noun","an opinion"]],
  "g5-u09-brisk": [["adjective","active and energetic"],["adjective","quick"]],
  "g5-u09-cherish": [["verb","hold in deep affection"]],
  "g5-u09-considerate": [["adjective","careful not to inconvenience or harm others"]],
  "g5-u09-displace": [["verb","move something from its position"],["verb","take the place of"]],
  "g5-u09-downfall": [["noun","a sudden fall from power or position"],["noun","something that causes ruin"]],
  "g5-u09-estimate": [["verb","roughly calculate the value or extent of"],["noun","a rough calculation"]],
  "g5-u09-humiliate": [["verb","make someone feel ashamed or foolish"]],
  "g5-u09-identical": [["adjective","exactly the same"],["adjective","similar in every detail"]],
  "g5-u09-improper": [["adjective","not in accordance with rules or standards"]],
  "g5-u09-poll": [["noun","a survey of people's opinions"],["verb","ask for opinions"]],
  "g5-u09-soothe": [["verb","calming or soothing"],["verb","reduce pain or discomfort"]],
  "g5-u09-vicinity": [["noun","the area near or surrounding a particular place"]],
  "g5-u10-abolish": [["verb","officially end a law or system"]],
  "g5-u10-appeal": [["verb","make a serious request for help"],["verb","be attractive"],["noun","a serious request"]],
  "g5-u10-brittle": [["adjective","hard but liable to break easily"]],
  "g5-u10-condemn": [["verb","express disapproval of"],["verb","sentence to punishment"]],
  "g5-u10-descend": [["verb","move or fall downward"],["verb","originate from"]],
  "g5-u10-dictator": [["noun","a ruler who has total power"]],
  "g5-u10-expand": [["verb","become or make larger"],["verb","give more details"]],
  "g5-u10-famine": [["noun","extreme scarcity of food"]],
  "g5-u10-portable": [["adjective","able to be easily carried"]],
  "g5-u10-prey": [["noun","an animal hunted and killed for food"],["verb","pursue and kill"],["verb","exploit"]],
  "g5-u10-thrifty": [["adjective","using money and other resources carefully"]],
  "g5-u10-visual": [["adjective","relating to seeing or sight"]],
  "g5-u11-absurd": [["adjective","illogical or absurdly unreasonable"]],
  "g5-u11-avalanche": [["noun","a mass of snow sliding down a mountain"],["verb","come down as an avalanche"]],
  "g5-u11-classify": [["verb","arrange in classes or categories"]],
  "g5-u11-ensure": [["verb","make certain that something happens or is the case"]],
  "g5-u11-navigate": [["verb","plan and direct route of"],["verb","get around on"]],
  "g5-u11-nestle": [["verb","settle or lie comfortably within or against"]],
  "g5-u11-plea": [["noun","a serious and emotional request for help"],["noun","a statement made by or for someone charged with an offense"]],
  "g5-u11-principle": [["noun","a fundamental truth or assumption"],["noun","a rule of conduct"]],
  "g5-u11-realistic": [["adjective","having or showing a sensible and practical idea of what can be achieved"]],
  "g5-u11-security": [["noun","the state of being free from danger or threat"],["noun","measures taken to protect"]],
  "g5-u11-selective": [["adjective","relating to or using selection"],["adjective","exclusive or fussy"]],
  "g5-u11-tart": [["adjective","sharp or sour in taste"],["adjective","sharp or critical"],["noun","a baked dish with filling"]],
  "g5-u12-abuse": [["verb","use something incorrectly"],["verb","treat with cruelty or violence"],["noun","improper use"],["noun","ill-treatment"]],
  "g5-u12-appliance": [["noun","a device or piece of equipment designed to perform a specific function"]],
  "g5-u12-confirm": [["verb","establish as true or valid"],["verb","verify or agree to"]],
  "g5-u12-daze": [["verb","make stunned or confused"],["noun","a state of stunned confusion"]],
  "g5-u12-flimsy": [["adjective","insubstantial and easily damaged"]],
  "g5-u12-gauge": [["noun","an instrument for measuring"],["verb","estimate or determine"]],
  "g5-u12-migrant": [["noun","a person who moves from one region to another"],["adjective","relating to migration"]],
  "g5-u12-neutral": [["adjective","not supporting or opposing either side"],["adjective","without strong or distinctive qualities"]],
  "g5-u12-pitiless": [["adjective","showing no pity or mercy"]],
  "g5-u12-presentable": [["adjective","suitable to be presented to other people"]],
  "g5-u12-rotate": [["verb","move or cause to move in a circle around an axis"],["verb","take turns"]],
  "g5-u12-shred": [["noun","a small strip"],["verb","tear or cut into strips"]],
  "g5-u13-achievement": [["noun","a thing done successfully with effort or skill"],["noun","the process of achieving"]],
  "g5-u13-acquire": [["verb","get as one's own"],["verb","gain by learning or experience"]],
  "g5-u13-debate": [["noun","a formal discussion of a subject in a public meeting"],["verb","discuss"]],
  "g5-u13-exhibit": [["verb","show for public appreciation"],["noun","a public display of art or items of interest"]],
  "g5-u13-foe": [["noun","an enemy"],["noun","something harmful"]],
  "g5-u13-latter": [["adjective","situated or occurring nearer to the end of something"],["adjective","used to indicate the second of two things"]],
  "g5-u13-massacre": [["noun","an indiscriminate slaughter of people"],["verb","slaughter many people brutally"]],
  "g5-u13-monotonous": [["adjective","dull, tedious, and repetitive"]],
  "g5-u13-preserve": [["verb","keep something in its original state"],["noun","a place of conservation"]],
  "g5-u13-sanitary": [["adjective","relating to health"],["adjective","clean and hygienic"]],
  "g5-u13-sprawl": [["verb","spread out in an untidy way"],["verb","be awkwardly stretched or spread out"]],
  "g5-u13-widespread": [["adjective","found or distributed over a large area or number of people"]],
  "g5-u14-alibi": [["noun","a claim or evidence that someone was somewhere else when a crime was committed"]],
  "g5-u14-confederate": [["noun","a person one works with, especially secretly in a dishonest activity"],["verb","join together"],["adjective","united"]],
  "g5-u14-discharge": [["verb","allow to leave"],["verb","pour out"],["verb","perform duties"],["noun","the process of discharging"]],
  "g5-u14-economical": [["adjective","giving good value in relation to the cost"],["adjective","using resources carefully"]],
  "g5-u14-frank": [["adjective","open, honest, and direct in speech or writing"]],
  "g5-u14-modify": [["verb","make partial changes to"]],
  "g5-u14-mutiny": [["noun","an open rebellion against the proper authorities"],["verb","engage in mutiny"]],
  "g5-u14-negative": [["adjective","expressing refusal or denial"],["noun","a negative statement or answer"],["noun","a photographic image"]],
  "g5-u14-pursue": [["verb","follow in order to catch or attack"],["verb","continue with determination"]],
  "g5-u14-reign": [["noun","the period of rule of a monarch"],["verb","rule"],["verb","be the dominant quality"]],
  "g5-u14-singular": [["adjective","exceptionally great or remarkable"],["adjective","of or belonging to a single person or thing"],["noun","the form of a word that denotes one thing"]],
  "g5-u14-swindle": [["verb","cheat someone out of money"],["noun","an instance of swindling"]],
  "g5-u15-complicate": [["verb","make more difficult"],["verb","involve"]],
  "g5-u15-courteous": [["adjective","polite, respectful, or considerate"]],
  "g5-u15-discomfort": [["noun","slight pain or unease"],["verb","make feel uneasy"]],
  "g5-u15-eliminate": [["verb","completely remove or get rid of"]],
  "g5-u15-grieve": [["verb","feel great sorrow"],["verb","mourn"]],
  "g5-u15-moral": [["adjective","relating to principles of right and wrong"],["noun","a lesson or principle concerning right or wrong"]],
  "g5-u15-scorch": [["verb","burn the surface of something with flame or heat"],["noun","a mark caused by scorching"]],
  "g5-u15-severe": [["adjective","very great"],["adjective","strict or harsh"],["adjective","extremely bad"]],
  "g5-u15-spectacle": [["noun","a visually striking performance or display"],["noun","eyeglasses"]],
  "g5-u15-tragic": [["adjective","causing or characterized by extreme distress or sorrow"]],
  "g5-u15-trifle": [["noun","a thing of little value or importance"],["verb","treat without seriousness"]],
  "g5-u15-universal": [["adjective","relating to all people or things in the world"],["adjective","applicable everywhere"]],
  "g5-u16-assume": [["verb","accept without proof"],["verb","undertake or take on"]],
  "g5-u16-cram": [["verb","force into a small space"],["verb","study intensively"]],
  "g5-u16-endanger": [["verb","put at risk or in danger"]],
  "g5-u16-fare": [["verb","perform in a particular way"],["noun","the money a passenger pays"],["noun","food"]],
  "g5-u16-fertile": [["adjective","producing many new plants or animals"],["adjective","capable of producing good results"]],
  "g5-u16-furnish": [["verb","provide with furniture"],["verb","provide with necessary things"]],
  "g5-u16-mammoth": [["adjective","extremely large"],["noun","the name of certain large extinct animals"]],
  "g5-u16-peer": [["verb","look carefully with difficulty"],["noun","a person of the same age or status"]],
  "g5-u16-rigid": [["adjective","unable to bend or be forced out of shape"],["adjective","unable or unwilling to adapt"]],
  "g5-u16-rowdy": [["adjective","noisy and disorderly"]],
  "g5-u16-safeguard": [["noun","a precautionary measure against possible risk"],["verb","protect"]],
  "g5-u16-trespass": [["verb","enter someone's land without permission"],["noun","an act of trespassing"]],
  "g5-u17-accumulate": [["verb","gather or collect"],["verb","gradually build up"]],
  "g5-u17-compromise": [["noun","an agreement reached by mutual concessions"],["verb","settle a dispute by making concessions"],["verb","put at risk"]],
  "g5-u17-desolate": [["adjective","empty and sad looking"],["adjective","miserably unhappy"],["verb","make feel utterly wretched"]],
  "g5-u17-disregard": [["verb","pay no attention to"],["noun","lack of consideration"]],
  "g5-u17-emphasis": [["noun","special importance given to something"],["noun","prominence given to syllables in speech"]],
  "g5-u17-friction": [["noun","the resistance when one surface rubs against another"],["noun","a conflict or disagreement"]],
  "g5-u17-intervene": [["verb","interfere to alter a situation"],["verb","interrupt an event"]],
  "g5-u17-irresistible": [["adjective","too attractive and tempting to resist"],["adjective","too strong to resist"]],
  "g5-u17-majority": [["noun","the greater number of"],["noun","the larger number of votes"]],
  "g5-u17-phenomenon": [["noun","a fact or event considered to be in existence or known"],["noun","something extraordinary or remarkable"]],
  "g5-u17-profound": [["adjective","very great or intense"],["adjective","showing deep insight"]],
  "g5-u17-subside": [["verb","become less intense, violent, or severe"],["verb","sink to a lower level"]],
  "g5-u18-advocate": [["verb","publicly support a particular cause or policy"],["noun","a person who publicly supports a cause or policy"]],
  "g5-u18-anticipate": [["verb","regard as probable; expect"],["verb","act in advance of"]],
  "g5-u18-concept": [["noun","an abstract idea; a general notion"]],
  "g5-u18-contradict": [["verb","deny the truth of"],["verb","be in conflict with"]],
  "g5-u18-extract": [["verb","remove or take out"],["verb","obtain from a source"],["noun","a short passage taken from text"]],
  "g5-u18-fundamental": [["adjective","forming a base or foundation"],["adjective","of central importance"],["noun","a basic principle"]],
  "g5-u18-ignorance": [["noun","lack of knowledge or awareness"]],
  "g5-u18-internal": [["adjective","of or situated on the inside"],["adjective","existing within an organization"]],
  "g5-u18-preliminary": [["adjective","denoting something done to prepare for something else"],["noun","an action undertaken in preparation for something"]],
  "g5-u18-premise": [["noun","a previous statement or proposition from which another is inferred"],["noun","a building and its surrounding land"],["verb","base an argument on"]],
  "g5-u18-retain": [["verb","continue to have"],["verb","keep in place"],["verb","employ a professional adviser"]],
  "g5-u18-significant": [["adjective","sufficiently great or important to be worthy of attention"]],
  "g1-u01-empty": [["adjective","containing nothing; not filled or occupied"]],
  "g1-u02-fog": [["noun","a thick cloud of tiny water droplets suspended in the air near the ground"],["verb","become covered with fog"]],
  "g1-u03-area": [["noun","a region or part of a town, country, or the world"],["noun","the amount of space within a boundary"]],
  "g1-u03-gather": [["verb","come together or bring things together"],["verb","collect information"]],
  "g1-u03-market": [["noun","a regular gathering for buying and selling goods"],["noun","trade in a particular type of product"]],
  "g1-u03-price": [["noun","the amount of money expected or required in payment for something"],["verb","fix the price of"]],
  "g1-u03-rapid": [["adjective","happening quickly or promptly"],["plural noun","a part of a river with fast-flowing water"]],
  "g1-u03-ripe": [["adjective","(of fruit or grain) fully grown and ready to be harvested or eaten"]],
  "g1-u03-seller": [["noun","a person who sells something"]],
  "g1-u03-surround": [["verb","be all around something"],["verb","move into position around"]],
  "g1-u04-freezing": [["adjective","very cold"],["adjective","(of temperatures) at or below freezing point"]],
  "g1-u04-protect": [["verb","keep safe from harm or injury"]],
  "g1-u04-slide": [["verb","move smoothly along a surface"],["verb","gradually decline"],["noun","a smooth descent"]],
  "g1-u04-temperature": [["noun","a degree of measurement of heat or cold"]],
  "g1-u10-footprint": [["noun","the impression left by a foot on a surface"],["noun","a rough measure of size or effect"]],
  "g2-u01-evening": [["noun","the period of time at the end of the day, usually from about six o'clock to bedtime"]],
  "g2-u02-crowd": [["noun","a large number of people gathered together"],["verb","fill a place"]],
  "g2-u03-idea": [["noun","a thought or suggestion as to a possible course of action"],["noun","a mental impression"]],
  "g2-u03-seashell": [["noun","the shell of a sea mollusk"]],
  "g2-u03-stack": [["verb","arrange in a pile"],["noun","a pile of something"]],
  "g2-u03-tiny": [["adjective","very small"]],
  "g2-u14-attach": [["verb","join or fasten onto"]],
  "g4-u01-drowsy": [["adjective","sleepy"]],
  "g4-u01-suitable": [["adjective","right or appropriate for a particular purpose"]],
  "g4-u14-huddle": [["verb","crowd together closely"]],
  "g4-u15-merit": [["noun","the quality of being particularly good or worthy"],["verb","deserve"]],
  "g4-u16-adorn": [["verb","make more beautiful or attractive"]],
  "g4-u16-appropriate": [["adjective","suitable or proper in the circumstances"]],
  "g4-u16-assemble": [["verb","gather together in one place"],["verb","fit together component parts"]],
  "g4-u16-colossal": [["adjective","extremely large"]],
  "g4-u16-effective": [["adjective","producing a desired or intended result"]],
  "g4-u16-frail": [["adjective","easily damaged or broken"],["adjective","physically weak"]],
  "g4-u16-hostage": [["noun","a person held captive by another party as a guarantee of compliance"]],
  "g4-u16-landslide": [["noun","a collapse of a mass of earth or rock from a mountain or cliff"],["noun","a large majority of votes"]],
  "g4-u16-rampage": [["noun","a violent or unrestrained behavior"],["verb","behave in a violent or unrestrained way"]],
  "g4-u16-scamper": [["verb","run with quick light steps"]],
  "g4-u16-symptom": [["noun","a physical or mental feature indicating a condition or problem"]],
  "g4-u16-warrant": [["noun","an official authorization"],["verb","justify or necessitate"]],
  "g4-u17-approximate": [["adjective","close to the actual but not exactly correct"],["verb","come near to"]],
  "g4-u17-construct": [["verb","build or make"],["verb","invent"]],
  "g4-u17-crude": [["adjective","in a natural or raw state; not yet processed"],["adjective","rudely or coarsely made"]],
  "g4-u17-decline": [["verb","become smaller or fewer"],["verb","refuse politely"],["noun","a downward slope"]],
  "g4-u17-distinct": [["adjective","different in kind"],["adjective","easily audible or visible"]],
  "g4-u17-evident": [["adjective","clear to the eye or mind"]]
  };
  window.DefinitionsData = {
    get: function (wordId) { return (data[wordId] || []).map(function (d) { return { partOfSpeech: d[0] || '', definition: d[1] || '' }; }); },
    has: function (wordId) { return !!(data[wordId] && data[wordId].length); }
  };
})();
